// All course data for Radian H.A. Limited Training
window.COURSES_DATA = {

  'cisrs-l1': {
    category: 'cisrs',
    code: 'CISRS-L1',
    title: 'CISRS OSTS Scaffolder Level 1',
    duration: '5 Days',
    courseType: 'CISRS OSTS Scaffold Training',
    trainingTime: '8:00 a.m. – 4:00 p.m.',
    price: '8,437.50',
    whoShouldAttend: 'This course is aimed at trainee scaffolders who require basic scaffolding skills training.',
    prerequisites: 'This course is aimed at delegates who have a minimum of 6 months practical experience of scaffolding operations.',
    objectives: 'To provide delegates with the knowledge and skills to enable them to erect, alter and dismantle basic scaffolding structures in traditional tube and fitting and common system scaffold types. Level 1 scaffolders can only lead scaffold gangs when working on structures covered by their training. They are deemed competent to work on higher and more complex structures providing they are under the direct supervision of a suitably qualified scaffolder.',
    careerPath: 'Scaffolders can progress to CISRS OSTS Scaffolder Level 2 after six (6) months further relevant scaffolding experience.',
    ppe: [
      'Safety footwear with protective toe (toe cap should not be showing)',
      'Appropriate work clothing e.g., overalls or shirt and long pants',
    ],
    ppeNote: 'Scaffolding kits with all the necessary tools and gears will be provided: a helmet, gloves, harness, lanyard and other scaffolding equipment.',
    certifications: '– Successful delegates will receive a CISRS OSTS Scaffolder Level 1 Certificate of Training and Record Card.<br/>– Certificates and cards are valid for 5 years as outlined on the card.',
    curriculum: {
      theoryTitle: 'Core Theory Units',
      theory: [
        'General Health and Safety Awareness',
        'International Best Practice',
        'International Performance Standards',
        'Local Legal Requirements',
        'Components / Materials Recognition',
        'Manual Handling (NASC Document SG6)',
        'Fall Prevention (NASC Document SG4)',
        'Foundations / Integrity and Stability (Bracing & Ties, etc.)',
        'Access and Egress',
      ],
      practicalTitle: 'Practical Units',
      practical: [
        { title: 'Static and Mobile Tower', sub: '2 Lifts including foot tie — two static and one mobile for demo' },
        { title: 'Independent with Return', sub: '2 Lifts including foot tie' },
        { title: 'Nine Standard Birdcage Scaffold', sub: '2 Lifts including foot tie' },
        'Practical / Theory Test',
      ],
    },
  },

  'cisrs-l2': {
    category: 'cisrs',
    code: 'CISRS-L2',
    title: 'CISRS OSTS Scaffolder Level 2',
    duration: '5 Days',
    courseType: 'CISRS OSTS Scaffold Training',
    trainingTime: '8:00 a.m. – 4:00 p.m.',
    price: '8,437.50',
    whoShouldAttend: 'This course is aimed at delegates who have completed CISRS Level 1 and want to further their career path in scaffolding or their job requires an advanced understanding of scaffolding structures.',
    prerequisites: 'Delegates must have completed the CISRS OSTS Scaffolder Level 1 course and have held the card for at least 6 months.',
    objectives: 'To provide delegates with the knowledge and skills to enable them to erect, alter and dismantle scaffolding structures of an intermediate complexity in traditional tube and fitting and common system scaffold types. Level 2 scaffolders can only lead scaffold gangs when working on structures covered by their CISRS training. They are deemed competent to work on more complex structures providing they are under the direct supervision of a suitably qualified CISRS scaffolder.',
    careerPath: 'Scaffolders can progress to CISRS OSTS Scaffolder Level 3 after 6 months of further relevant scaffolding experience.',
    ppe: [
      'Safety footwear with protective toe (toe cap should not be showing)',
      'Appropriate work clothing e.g., overalls or shirt and long pants',
    ],
    ppeNote: 'Scaffolding kits with all the necessary tools and gears will be provided: a helmet, gloves, harness, lanyard and other scaffolding equipment.',
    certifications: '– Successful delegates will receive a CISRS OSTS Scaffolder Level 2 Certificate of Training and Record Card.<br/>– Certificates and cards are valid for 5 years as outlined on the card.',
    curriculum: {
      theoryTitle: 'Core Theory Units',
      theory: [
        'International Best Practice',
        'International Performance Standards',
        'Local Legal Requirements',
        'Components / Materials Recognition',
        'Working with Scaffold Designs',
        'Manual Handling (NASC Document SG6)',
        'Fall Prevention (NASC Document SG4)',
        'Foundations / Integrity and Stability (Bracing & Ties, etc.)',
        'Access and Egress',
      ],
      practicalTitle: 'Practical Units',
      practical: [
        'Delegate Skills Check',
        { title: 'Simple Cantilever with Spurs', sub: 'Erected from independent scaffold' },
        'Gantry / Crash Deck',
        'Crane Loading Bay',
        'Edge Protection / Handrails',
        'Practical / Theory Test',
      ],
    },
  },

  'cisrs-l3': {
    category: 'cisrs',
    code: 'CISRS-L3',
    title: 'CISRS OSTS Scaffolder Level 3',
    duration: '5 Days',
    courseType: 'CISRS OSTS Scaffold Training',
    trainingTime: '8:00 a.m. – 4:00 p.m.',
    price: '9,000.00',
    whoShouldAttend: 'This course is aimed at delegates who have completed CISRS Level 2 and want to further their career path in scaffolding or their job requires an advanced understanding of scaffolding structures.',
    prerequisites: 'Delegates must have completed the CISRS Level 2 Overseas Scaffolder 5 Day Course and have held the card for at least 6 months.',
    objectives: 'To provide delegates with the knowledge and skills to enable them to erect, alter and dismantle scaffolding structures of a more complex nature than those undertaken in the Level 2 course. Level 3 scaffolders can only lead scaffold gangs when working on structures covered by their CISRS training. They are deemed competent to work on more complex structures providing they are under the direct supervision of a suitably qualified CISRS scaffolder.',
    careerPath: 'Scaffolders can progress to Level 4 Overseas Scaffolder after a minimum of 12 months of further relevant scaffolding experience.',
    ppe: [
      'Safety footwear with protective toe (toe cap should not be showing)',
      'Appropriate work clothing e.g., overalls or shirt and long pants',
    ],
    ppeNote: 'Scaffolding kits with all the necessary tools and gears will be provided: a helmet, gloves, harness, lanyard and other scaffolding equipment.',
    certifications: '– Successful delegates will receive a CISRS OSTS Scaffolder Level 3 Certificate of Training and Record Card.<br/>– Certificates and cards are valid for 5 years as outlined on the card.<br/>– To renew this card, delegates must attend a Level 3 CPD Refresher Course.',
    curriculum: {
      theoryTitle: 'Core Theory Units',
      theory: [
        'International Best Practice',
        'International Performance Standards',
        'Local Legal Requirements',
        'Designed Scaffolds',
        'Components / Materials Recognition',
        'Manual Handling (NASC Document SG6)',
        'Fall Prevention (NASC Document SG4)',
        'Foundations / Integrity and Stability (Bracing & Ties, etc.)',
        'Access and Egress',
      ],
      practicalTitle: 'Practical Units',
      practical: [
        'Delegate Skills Check',
        { title: 'Bridging with Tube and Fitting and Beams from Independent', sub: 'Bridge scaffold with spurs / V brace in tube and fitting, then alter to include beams' },
        'Lifting Frame',
        'Splay / Radial',
        'Practical / Theory Test',
      ],
    },
  },

  'cisrs-basic-inspection': {
    category: 'cisrs',
    code: 'CISRS-BI',
    title: 'CISRS OSTS Basic Scaffold Inspection',
    duration: '3 Days',
    courseType: 'CISRS OSTS Scaffold Training',
    trainingTime: '8:00 a.m. – 4:00 p.m.',
    price: '6,750.00',
    whoShouldAttend: 'This course is aimed at scaffolders & non-scaffolders e.g., Managers / Engineers who are required to carry out inspections of basic scaffold structures. These structures are those that are included in Level 1, 2 and 3 Scaffolder training courses.',
    prerequisites: 'Individuals who meet at least one of the following will be deemed to have met the entry criteria:<br/>– Holds a current OSTS Level 3 card or above<br/>– Holds a current OSTS Supervisor card<br/>– Holds a current or expired OSTS Basic Scaffold Inspection card<br/><br/>Individuals not holding one of these CISRS cards will be required to submit a CV detailing their scaffolding work experience and CISRS Basic Scaffold Inspection Delegate Check Form with contactable references and/or certificates. They must have a minimum of 2 years of scaffolding industry experience.<br/><br/>Delegates are also required to have awareness and experience of scaffolding structures, which would have come from time spent in their individual industry sector e.g., construction, engineering, manufacturing, petrochemical, oil, and gas etc.',
    objectives: 'To provide delegates with the knowledge and skills to enable them to inspect basic scaffold structures and complete safety inspection reports.',
    careerPath: 'Basic Scaffold Inspectors are required to hold the card for a minimum of two years prior to the attendance of an Advanced Scaffold Inspection Course.',
    ppe: [
      'Safety footwear with protective toe (toe cap should not be showing)',
      'Appropriate clothing',
      'Helmet (if necessary, we can provide helmets for participants)',
    ],
    certifications: '– Successful delegates will receive a CISRS OSTS Basic Scaffold Inspector Certificate of Training and Record Card.<br/>– Certificates and cards are valid for 5 years as outlined on the card.',
    curriculum: {
      theoryTitle: 'Core Theory Units',
      theory: [
        'Introduction to Scaffolding and Scaffolding Terminology',
        'Statutory Requirements and Codes of Practice',
        'International Standards (British, European, US & Local)',
        'International Best Practice & Industry Standards (NASC)',
        'Overview of Fall Prevention in Scaffolding',
        'Tube, Fittings & Boards',
        'Safe Access and Egress',
        'Scaffolders Training and Working Methods',
        'Bracing and Tying Scaffolds',
        'Mobile, Static, and Loading Towers',
        'Birdcage Scaffolds',
        'Beams and Bridging Beams',
        'Public Protection',
        'Various Types of System Scaffolding',
        'How to Carry Out a Scaffolding Inspection',
        'Scaffold Inspection Reports',
        'Scaffold Tagging Systems',
        'Practical Scaffold Inspection Exercises',
        'Knowledge Test and Assessment',
      ],
      practical: null,
    },
  },

  'cisrs-advanced-inspection': {
    category: 'cisrs',
    code: 'CISRS-AI',
    title: 'CISRS OSTS Advanced Scaffold Inspection',
    duration: '2 Days',
    courseType: 'CISRS OSTS Scaffold Training',
    trainingTime: '8:00 a.m. – 4:00 p.m.',
    price: '6,500.00',
    whoShouldAttend: 'This course is aimed at those who are required to carry out safety inspections for complex designed structures.',
    prerequisites: 'To be able to attend this course, delegates must have held a CISRS OSTS Basic Inspection Card or CISRS OSTS Level 3 card for at least 2 years.',
    objectives: 'To provide delegates with such knowledge and skills to enable them to inspect complex designed structures and complete safety inspection reports.',
    ppe: [
      'Safety footwear with protective toe (toe cap should not be showing)',
      'Appropriate clothing',
      'Helmet (if necessary, we can provide helmets for participants)',
    ],
    certifications: '– Successful delegates will receive a CISRS OSTS Advanced Scaffold Inspector Certificate of Training and Record Card.<br/>– Certificates and cards are valid for 5 years as outlined on the card.',
    curriculum: {
      theoryTitle: 'Core Theory Units',
      theory: [
        'Statutory Requirements & Codes of Practice',
        'International Standards (British, European, US & Local)',
        'International Best Practice & Industry Standards (NASC)',
        'Overview of Fall Prevention in Scaffolding',
        'Advanced Component Information',
        'Review of Basic Structures',
        'Scaffold Design Overview & Interpreting Drawings',
      ],
      practicalTitle: 'Advanced Scaffold Structures',
      practical: [
        'Suspended Scaffolds',
        'Cantilevered Scaffolds',
        'Splayed / Radial Scaffolds',
        { title: 'Shores', sub: 'Dead, Raking, Flying' },
        'Ramps & Gangways',
        { title: 'Staircases', sub: 'Tube and Fitting' },
        'Scaffold Inspection in Practice',
        'Scaffold Inspection Reports',
        'Scaffold Tagging Systems',
        'Practical Scaffold Inspection Exercises',
        'Knowledge Test and Assessment',
      ],
    },
  },

  'cisrs-supervisor': {
    category: 'cisrs',
    code: 'CISRS-SUP',
    title: 'CISRS OSTS Scaffold Supervisor',
    duration: '3 Days',
    courseType: 'CISRS OSTS Scaffold Training',
    trainingTime: '8:00 a.m. – 4:00 p.m.',
    price: '7,875.00',
    whoShouldAttend: 'This course is aimed at those who are responsible for the supervision, direction and instruction of scaffolding operations e.g. Charge Hands, Foreman, Supervisors, Contract Supervisors and Management.',
    prerequisites: 'To be able to attend this course, delegates are required to have a minimum of 5 years of scaffolding industry experience and should ideally hold a CISRS Scaffolder Level 3 or 4 qualifications (or equivalent).<br/><br/>Individuals will be required to submit a CV detailing their scaffolding work experience and complete a CISRS Supervisor Delegate Check Form with contactable references and/or certificates. This form will need to include confirmation from an employer that the delegate has awareness and experience of scaffolding structures gained via their role within the industry and confirmation that the delegate has had a minimum of 5 years of experience in this role.',
    objectives: 'To give the delegates such knowledge and skills to enable them to supervise, monitor, direct and instruct Scaffolders in scaffolding operations.',
    ppe: [
      'Safety footwear with protective toe (toe cap should not be showing)',
      'Appropriate clothing',
      'Helmet (if necessary, we can provide helmets for participants)',
    ],
    certifications: '– Successful delegates will receive a CISRS OSTS Scaffold Supervisor certificate and CISRS OSTS Supervisor card.<br/>– Certificates and cards are valid for 5 years as outlined on the card.',
    curriculum: {
      theoryTitle: 'Core Theory Units',
      theory: [
        'Legal Overview (Local Regulation for the country or region)',
        'Performance Standards',
        { title: 'Communication Skills', sub: 'Including Task Briefings & Toolbox Talks' },
        'Supervisory Skills',
        'Design Appreciation',
        'Theory Tests',
        { title: 'Practical Exercises', sub: 'Scaffold Inspection & Toolbox Talks' },
        'Risk Assessment Project',
      ],
      practical: null,
    },
  },

  'gms-wah': {
    category: 'wah',
    code: 'GMS-WAH',
    title: 'Getmie Safe Working at Height',
    duration: '1 Day',
    courseType: 'Getmie Safe Working at Height & Rescue Training',
    trainingTime: '8:00 a.m. – 4:00 p.m.',
    price: '675.00',
    whoShouldAttend: 'This course is aimed at scaffolders, as well as any other personnel who regularly work at heights or are exposed to falls from height in the workplace.',
    prerequisites: 'This course is aimed at delegates who are currently performing Work at Heights duties.',
    objectives: 'To gain general knowledge regarding safe practices and requirements for general Work at Height.',
    ppe: [
      'Safety footwear with protective toe (toe cap should not be showing)',
      'Appropriate work clothing e.g., overalls',
    ],
    ppeNote: 'All the necessary tools and gears will be provided for demonstration purposes.',
    certifications: '– Successful delegates will receive a digital certificate.<br/>– Reassessment is required after 36 months.',
    curriculum: {
      theoryTitle: 'Course Contents',
      theory: [
        { title: 'Theoretical and Practical Applications', sub: 'Understand the requirements to carry out general Work at Height safely' },
        { title: 'Risk Assessments', sub: 'Understand the hierarchy of Work at Height with regards to selection of equipment' },
        { title: 'Pre-use Inspections', sub: 'Carry out pre-use inspections of selected Work at Height PPE' },
        { title: 'Equipment Competence', sub: 'Gain competence in the use of various Work at Height equipment for restraint, work positioning and fall arrest' },
        'Written examination at the end of training',
      ],
      practical: null,
    },
  },

  'gms-rescue-basic': {
    category: 'rescue',
    code: 'GMS-RB',
    title: 'Basic Getmie Safe Rescue Training',
    duration: '1 Day',
    courseType: 'Getmie Safe Working at Height & Rescue Training',
    trainingTime: '8:00 a.m. – 4:00 p.m.',
    price: '1,687.50',
    whoShouldAttend: 'This course is aimed at scaffolders or any other personnel who are tasked with carrying out rescue from areas at height and confined space.',
    prerequisites: 'This course is aimed at delegates who have completed prior Working at Height training.',
    objectives: 'To gain general knowledge regarding safe practices and requirements for the use of "Fast Access" rescue device for basic rescue, and to gain practical skills in the safe operation of equipment and associated work at height harnesses including safe attachment points for rescue and evacuation from heights.',
    specifications: '– Fast Access equipment at Rescue level (Basic Rescue).',
    ppe: [
      'Safety footwear with protective toe (toe cap should not be showing)',
      'Appropriate work clothing e.g., overalls',
    ],
    ppeNote: 'Rescue kits with all the necessary tools and gears will be provided, as well as individual items, such as: helmet, gloves, harness, lanyard etc.',
    certifications: '– Successful delegates will receive a digital certificate.<br/>– Refresher training is required every 12 months (year).',
    curriculum: {
      theoryTitle: 'Course Contents',
      theory: [
        { title: 'Review of Emergency Planning and Equipment', sub: 'Reinforce understanding of rescue preparedness and equipment readiness' },
        { title: 'Personal Protective Equipment (PPE) and Safety Protocols', sub: 'Knowledge of appropriate PPE use and hazard control during rescues' },
        { title: 'Demonstrations and Practical Drills', sub: 'Familiarise with key rescue systems and ensure continued proficiency' },
        { title: 'Essential Rescue Techniques', sub: 'Maintain competence in a range of basic rescue scenarios' },
        { title: 'Team-Based Rescue Simulations', sub: 'Practice coordinated rescues under time pressure and review decision-making' },
        { title: 'Rescue Leadership and Incident Control', sub: 'Reinforce individual responsibility and control in line with emergency plans' },
        { title: 'Practical Examination',
          sub: 'At the end of training, covering:',
          bullets: ['Equipment inspection and setup', 'Device handling and operation', 'Execution of selected rescue scenarios'] },
      ],
      practical: null,
    },
  },

  'gms-rescue-advanced': {
    category: 'rescue',
    code: 'GMS-RA',
    title: 'Advanced Getmie Safe Rescue Training',
    duration: '2 Days',
    courseType: 'Getmie Safe Working at Height & Rescue Training',
    trainingTime: '8:00 a.m. – 4:00 p.m.',
    price: '3,375.00',
    whoShouldAttend: 'This course is aimed at scaffolders or any other personnel who are tasked with carrying out rescue from areas at height and confined space.',
    prerequisites: 'This course is aimed at delegates who have completed prior Working at Height training and Basic Getmie Safe Rescue training.',
    objectives: 'To gain general knowledge regarding safe practices and requirements for the use of "Fast Access" rescue device and the UniDrive and MaxDrive devices for rescue. To gain practical skills in the safe operation of equipment and associated work at height harnesses including safe attachment points for rescue and evacuation from heights and confined spaces.',
    ppe: [
      'Safety footwear with protective toe (toe cap should not be showing)',
      'Appropriate work clothing e.g., overalls',
    ],
    ppeNote: 'Rescue kits with all the necessary tools and gears will be provided, as well as individual items, such as: helmet, gloves, harness, lanyard etc.',
    certifications: '– Successful delegates will receive a digital certificate.<br/>– Refresher training is required every 12 months (year).',
    curriculum: {
      theoryTitle: 'Course Contents',
      theory: [
        { title: 'Determine Appropriate PPE', sub: 'Ensure safety during exercises through proper Personal Protective Equipment selection' },
        { title: 'Introduction to UniDrive and MaxDrive', sub: 'Familiarisation with advanced rescue devices' },
        { title: 'Practical Applications of Fast Access, UniDrive and MaxDrive',
          sub: 'Understand advanced rescue from height including:',
          bullets: ['Cross-hauling', 'Rescuer descending to suspended person', 'Descend through ladder access', 'Confined space rescue', 'Sked training'] },
      ],
      practical: null,
    },
  },

  'gms-rescue-refresher': {
    category: 'rescue',
    code: 'GMS-RR',
    title: 'Getmie Safe Rescue Refresher',
    duration: '1 Day',
    courseType: 'Getmie Safe Working at Height & Rescue Training',
    trainingTime: '8:00 a.m. – 4:00 p.m.',
    price: '1,687.50',
    whoShouldAttend: 'This course is aimed at delegates who completed either Basic or Advanced Getmie Safe Rescue training.',
    prerequisites: 'Valid Getmie Safe Working at Height and Basic or Advanced Getmie Safe Rescue training.',
    objectives: 'To refresh and validate the knowledge and practical skills required for effective and safe rescue operations at height, in confined spaces, and in various emergency scenarios, using either basic or advanced equipment and techniques.',
    specifications: '– Fast Access equipment at Rescue level (Basic Rescue).<br/>– Uni and Max Drives as rescue and working devices (Advanced Rescue).',
    ppe: [
      'Safety footwear with protective toe (toe cap should not be showing)',
      'Appropriate work clothing e.g., overalls',
    ],
    ppeNote: 'Rescue kits with all the necessary tools and gears will be provided, as well as individual items, such as: helmet, gloves, harness, lanyard etc.',
    certifications: 'Successful delegates will receive a digital certificate.',
    curriculum: {
      theoryTitle: 'Course Contents',
      theory: [
        { title: 'Review of Emergency Planning and Equipment', sub: 'Reinforce understanding of rescue preparedness and equipment readiness' },
        { title: 'Personal Protective Equipment (PPE) and Safety Protocols', sub: 'Refresh knowledge of appropriate PPE use and hazard control during rescues' },
        { title: 'Refresher Demonstrations and Practical Drills', sub: 'Re-familiarize with key rescue systems and ensure continued proficiency' },
        { title: 'Review and Perform Essential Rescue Techniques', sub: 'Maintain competence in a range of basic or advanced rescue scenarios' },
        { title: 'Team-Based Rescue Simulations', sub: 'Practice coordinated rescues under time pressure and review decision-making' },
        { title: 'Rescue Leadership and Incident Control', sub: 'Reinforce individual responsibility and control in line with emergency plans' },
        { title: 'Practical Examination',
          sub: 'At the end of training, covering:',
          bullets: ['Equipment inspection and setup', 'Device handling and operation', 'Execution of selected rescue scenarios'] },
      ],
      practical: null,
    },
  },

};
